strain_abbreviations = {
    "09COOKIES X PUNCH" :"09P",
    "9LB Hammer" :"9LB",
    "Alien OG X Garlic Breath" :"AGB",
    "Apple Fritter" :"AF",
    "Apple Pie" :"AP",
    "Astronaut Status" :"AS",
    "Atteberries" :"ATB",
    "Banana Mac" :"BMAC",
    "Banana Sherbert" :"BSH",
    "Banana Split" :"BS",
    "Beef Wellington" :"BW",
    "Billy" :"BIL",
    "Billy x Paul" :"BP",
    "Black Cherry Punch X Jelly Breath" :"BCP",
    "Blue Cheese" :"BC",
    "Brain Blast" :"BB",
    "Bulldozer" :"BD",
    "Cactus Breath" :"CB",
    "Cactus OG" :"COG",
    "Cake Crasher" :"CC",
    "Cherry Hills" :"CH",
    "Cherry Pie" :"CHP",
    "Cherry Sangria" :"CHS",
    "Chow Mein" :"CM",
    "Chow Mein x Paul" :"CMP",
    "Corner Surprise" :"CS",
    "Dante's Inferno x Paul" :"DIP",
    "Dantes inferno" :"DI",
    "DarkVoid" :"DV",
    "Deadhead og x bullk kush f3" :"DHBK",
    "Diesel Biscotti Sundae x Paul" :"DBSP",
    "Dino Meat #8 x Mr. Stinky (Stankasaurus)" :"STAK",
    "Dirty Wizard x Paul" :"DWP",
    "DISCO CANDY" :"DC",
    "DOSI X BULLY KUSH" :"DBK",
    "Dosido" :"DOSI",
    "Euro Fresh" :"EF",
    "FLINTSTONES X THE CANDY" :"FLC",
    "Forum x Face Off og (Samoas)" :"SAM",
    "Fried Applez" :"FA",
    "Fuego Matador" :"FM",
    "Fuego Matador x Paul" :"FMP",
    "Garlic Pie x Paul" :"GPP",
    "Garlic Reaper" :"GR",
    "Garlic Reaper X Bully Kush" :"GRBK",
    "Gator Breath" :"GB",
    "Gelato Mint" :"GM",
    "GG4 X THE CANDY" :"GG4C",
    "GMac X Bully Kush" :"GMB",
    "GMLato" :"GML",
    "GMO Cookies x Sophisticated Lad (Unicorn Poop)" :"UP",
    "GMO x Lurch (Mule Fuel)" :"MF",
    "GMOreoz x Mai Tai #4" :"GMOM",
    "Gorilla Candy" :"GC",
    "Gorilla Glue #4" :"GG4",
    "Gorilla Punch" :"GP",
    "Grandpa's Breath" :"GPB",
    "Grape Pie X Garlic Breath" :"GPGB",
    "Grapefruit x PCSD (Double Sour Grapefruit)" :"DSG",
    "Guicy Banger" :"GB",
    "HIFI 4G#9" :"HIFI",
    "Hot Coco" :"HC",
    "Huggies" :"HUG",
    "Ice Cream Cake Bx1" :"ICC",
    "Jamaica Runtz" :"JR",
    "Kush Mints x Purple Chem" :"KMPC",
    "La Beatnik" :"LAB",
    "Lemon Tree X Pchem" :"LTPC",
    "Lemon Zephyr" :"LZ",
    "LHB x Sunset Sherbert (SherbHead)" :"SH",
    "LHBx(Triangle kushx High Octanebx2)" :"LHBTK",
    "London Pound Cake" :"LPC",
    "Mac 1" :"MAC",
    "Mac x Alien Cheese (Mac N Cheese)" :"MNC",
    "Mango Chow Mein" :"MCM",
    "Mango Smoothie" :"MS",
    "Meathead" :"MH",
    "Old World Skunk" :"OWS",
    "Oreoz" :"OR",
    "Oreoz x Mendo Breath (Pure Michigan)" :"PURE",
    "Pineapple Shocker x Paul (Brain Blast)" :"BB",
    "POOKIE" :"POO",
    "Pookie x Paul" :"POOP",
    "Purple Chem" :"PC",
    "Purple Punch" :"PP",
    "Putrid Michigan" :"PUT",
    "Raspberry Sunset" :"RSUN",
    "Raspberry Sunset x Paul" :"PSUN",
    "RipSaw" :"RIPS",
    "Runtz x Paul" :"RP",
    "Secret Formula" :"SF",
    "Shock Wave" :"SW",
    "Slurricane F1" :"SLU",
    "Smooth Glue" :"SG",
    "SNOWMAN X PABLOS REVENGE" :"SMPR",
    "Snowman's Revenge" :"SR",
    "Sour Diesel x Blue Diesel (Blueberry Sour Diesel)" :"BSD",
    "Sour Diesel x Purest Indica" :"SDPI",
    "Sour Dough" :"SD",
    "Sour Grapefruit x PCSD (Double Sour Grapefruit)" :"DSG",
    "Sour Octane x SJG OG" :"SOSJ",
    "Sour Scout" :"SSC",
    "SOUR STRAWBERRY DIESEL" :"SSD",
    "Step Bro" :"SB",
    "StepBro x Paul" :"SBP",
    "Stuffed Strawberries" :"SS",
    "Sugar Babies" :"SUG",
    "Sundae Driver S1" :"SDS1",
    "Sunndy d X Mac F1" :"SDMAC",
    "Sunset Sherbert X Animal Cookies BX2" :"SSAC",
    "Sunset Sherbert X Raspberry Beret" :"SSR",
    "Sunshine Lime" :"SSL",
    "Super lemon Haze X Garlic Breath" :"SLHGB",
    "Tangie" :"TGIE",
    "Tangie x On Haze" :"TAN",
    "The Matrix" :"MAT",
    "Tina" :"TINA",
    "TKLato" :"TKL",
    "Violet Mints" :"VM",
    "WAVE 63" :"W63",
    "Wedding Cake" :"WC",
    "Wedding Cake x Mendo Breath F2 (Puta 2.0)" :"PUTA",
    "Weebo" :"WEE",
    "White Widow" :"WW",
    "Wicked Lime" :"WL",
    "Wicked Lime x Paul" :"WLP",
    "Wizard Punch" :"WP",
    "Wizard Scout Glue" :"WSG",
    "Wonka Bars" :"WB",
    "Z-Face" :"ZF",
    "Z-Face x Paul" :"ZFP"
}